# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lua53_config = debug
  rapidjson_config = debug
  moon_config = debug
  protobuf_config = debug
  mysql_config = debug
  aoi_config = debug
  rvo2_config = debug
endif
ifeq ($(config),release)
  lua53_config = release
  rapidjson_config = release
  moon_config = release
  protobuf_config = release
  mysql_config = release
  aoi_config = release
  rvo2_config = release
endif

PROJECTS := lua53 rapidjson moon protobuf mysql aoi rvo2

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lua53:
ifneq (,$(lua53_config))
	@echo "==== Building lua53 ($(lua53_config)) ===="
	@${MAKE} --no-print-directory -C build/lua53 -f Makefile config=$(lua53_config)
endif

rapidjson:
ifneq (,$(rapidjson_config))
	@echo "==== Building rapidjson ($(rapidjson_config)) ===="
	@${MAKE} --no-print-directory -C build/rapidjson -f Makefile config=$(rapidjson_config)
endif

moon: lua53 rapidjson aoi protobuf mysql rvo2
ifneq (,$(moon_config))
	@echo "==== Building moon ($(moon_config)) ===="
	@${MAKE} --no-print-directory -C build/moon -f Makefile config=$(moon_config)
endif

protobuf:
ifneq (,$(protobuf_config))
	@echo "==== Building protobuf ($(protobuf_config)) ===="
	@${MAKE} --no-print-directory -C build/protobuf -f Makefile config=$(protobuf_config)
endif

mysql:
ifneq (,$(mysql_config))
	@echo "==== Building mysql ($(mysql_config)) ===="
	@${MAKE} --no-print-directory -C build/mysql -f Makefile config=$(mysql_config)
endif

aoi:
ifneq (,$(aoi_config))
	@echo "==== Building aoi ($(aoi_config)) ===="
	@${MAKE} --no-print-directory -C build/aoi -f Makefile config=$(aoi_config)
endif

rvo2:
ifneq (,$(rvo2_config))
	@echo "==== Building rvo2 ($(rvo2_config)) ===="
	@${MAKE} --no-print-directory -C build/rvo2 -f Makefile config=$(rvo2_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/lua53 -f Makefile clean
	@${MAKE} --no-print-directory -C build/rapidjson -f Makefile clean
	@${MAKE} --no-print-directory -C build/moon -f Makefile clean
	@${MAKE} --no-print-directory -C build/protobuf -f Makefile clean
	@${MAKE} --no-print-directory -C build/mysql -f Makefile clean
	@${MAKE} --no-print-directory -C build/aoi -f Makefile clean
	@${MAKE} --no-print-directory -C build/rvo2 -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lua53"
	@echo "   rapidjson"
	@echo "   moon"
	@echo "   protobuf"
	@echo "   mysql"
	@echo "   aoi"
	@echo "   rvo2"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"